### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by meghakundu**
integrated homepage

### CODE REVIEW

**Comment by SamiurRahmanMukul** [comment]
@meghakundu Hello, I would appreciate guidance on **deploying** this project. Could you kindly provide documentation on how to deploy it on my **cPane**l to transition it into a **beta** project? Thank you.

**Comment by meghakundu** [comment]
Yes, I can help you with that. I will be sharing the doc within few hours.

**Comment by meghakundu** [comment]
> @meghakundu Hello, I would appreciate guidance on **deploying** this project. Could you kindly provide documentation on how to deploy it on my **cPane**l to transition it into a **beta** project? Thank you.

[deploy_cpanel.txt](https://github.com/SamiurRahmanMukul/laravel-project-instagram-clone/files/15344204/deploy_cpanel.txt)
transiting into beta project, i m not sure about it.

**Comment by SamiurRahmanMukul** [comment]
@meghakundu  ok, i deploy it shortly

**Pull request merged**
